MainSite/Models/FoodRegisterViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Foolproof;

namespace MainSite.Models
{
    public class FoodRegisterViewModel
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Food type")]
        public virtual int FoodTypeId { get; set; }


        public string CreationDate { get; set; }
        public int TakenAtId { get; set; }
        public string TakenAt { get; set; }
        public string FoodType { get; set; }
        public int UserId { get; set; }

    }
}

MainSite/Controllers/FoodRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Entity.Capture;
using Entity.Security;
using MainSite.Filters;
using MainSite.Models;
using Service;
using WebMatrix.WebData;

namespace MainSite.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class FoodRegisterController : Controller
    {
        private readonly IFoodRegisterService foodRegisterService;
        private readonly ITakenAtService takenAtService;
        private readonly IFoodTypeService foodTypeService;
        private readonly IUserService userService;

        private User loggedUser;

        private User LoggedUser
        {
            get
            {
                return loggedUser ?? (loggedUser = userService.GetById(WebSecurity.CurrentUserId));
            }
        }

        public FoodRegisterController(IFoodRegisterService foodRegisterService, ITakenAtService takenAtService, IFoodTypeService foodTypeService, IUserService userService)
        {
            this.foodRegisterService = foodRegisterService;
            this.takenAtService = takenAtService;
            this.foodTypeService = foodTypeService;
            this.userService = userService;
        }

        //
        // GET: /FoodRegister/
        [Authorize]
        public ActionResult Index()
        {
            InitializeDropDowns();
            return View();
        }

        [Authorize]
        public JsonResult GetById(int id)
        {
            InitializeDropDowns();
            var foodRegister = foodRegisterService.GetById(id);
            var aux = new FoodRegisterViewModel
            {
                Description = foodRegister.Description,
                CreationDate = String.Format("{0:dd/MM/yy hh:mm}", foodRegister.CreationDate),
                Id = foodRegister.Id,
                FoodType = ((List<FoodType>)(ViewBag.FoodTypes)).FirstOrDefault(f => f.Id == foodRegister.FoodTypeId).Description,
                TakenAt = ((List<TakenAt>)(ViewBag.TakenAts)).FirstOrDefault(t => t.Id == foodRegister.TakenAtId).Description
            };
            return Json(aux, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FoodRegisterViewModel entity)
        {
            InitializeDropDowns();
            if (ModelState.IsValid)
            {
                try
                {

                    var aux = new FoodRegister
                        {
                            Description = entity.Description,
                            //TakenAt = ((List<TakenAt>)ViewBag.TakenAts).FirstOrDefault(m => m.Id == entity.TakenAtId),
                            //FoodType = ((List<FoodType>)ViewBag.FoodTypes).FirstOrDefault(m => m.Id == entity.FoodTypeId),
                            //User = LoggedUser,
                            TakenAtId = entity.TakenAtId,
                            FoodTypeId = entity.FoodTypeId,
                            UserId = LoggedUser.Id
                        };

                    foodRegisterService.Insert(aux);
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("error", e);
                }
            }

            return PartialView("CreatePartial", entity);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FoodRegisterViewModel entity)
        {
            InitializeDropDowns();
            if (ModelState.IsValid)
            {
                var auxEntity = foodRegisterService.GetById(entity.Id);
                var message = auxEntity == null ? "This register don't exists!" :
                    !IsValidDateForModification(auxEntity) ? "You can't update the food register of yesterday or less" : "";
                if (!string.IsNullOrWhiteSpace(message))
                    throw new Exception(message);
                try
                {
                    var aux = new FoodRegister
                    {
                        Id = entity.Id,
                        Description = entity.Description,
                        FoodTypeId = entity.FoodTypeId
                    };

                    foodRegisterService.Update(aux);
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("error", e);
                }
            }

            return PartialView("CreatePartial", entity);
        }

        [Authorize]
        public JsonResult Remove(int id)
        {
            string message = "";
            try
            {
                var entity = foodRegisterService.GetById(id);
                message = entity == null ? "This register don't exists!" :
                    !IsValidDateForModification(entity) ? "You can't eliminate the food register of yesterday or less" :
                    foodRegisterService.Remove(id) <= 0 ? "Error eliminating this data" :
                    "Registry eliminated successfully";
            }
            catch (Exception ex)
            {
                message = "Unexpected error while eliminating this register." + (HttpContext.IsDebuggingEnabled ? " Details: <br/>" + ex.Message : "");
            }
            return Json(message, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public JsonResult GetFoodRegistersByLoggedUserAndDate(DateTime? date)
        {
            if (!date.HasValue)
                return Json(new { Message = "No valid datetime sent to the server" }, JsonRequestBehavior.AllowGet);
            InitializeDropDowns();
            var foodRegisters = foodRegisterService
                .GetByUserAndDate(LoggedUser, date.Value)
                .Select(m =>
                    {
                        var foodType = ((List<FoodType>)(ViewBag.FoodTypes)).FirstOrDefault(f => f.Id == m.FoodTypeId);
                        var takenAt = ((List<TakenAt>)(ViewBag.TakenAts)).FirstOrDefault(t => t.Id == m.TakenAtId);
                        return new FoodRegisterViewModel
                            {
                                Description = m.Description,
                                CreationDate = String.Format("{0:MM/dd/yyyy hh:mm}", m.CreationDate),
                                Id = m.Id,
                                FoodType = foodType.Description,
                                TakenAt = takenAt.Description,
                                TakenAtId = takenAt.Id,
                                FoodTypeId = foodType.Id,
                                UserId = m.UserId
                            };
                    })
                .ToList();
            return Json(foodRegisters, JsonRequestBehavior.AllowGet);
        }

        private bool IsValidDateForModification(FoodRegister entity)
        {
            var dateTime = DateTime.Now;
            return (dateTime.Day == entity.CreationDate.Day &&
                dateTime.Month == entity.CreationDate.Month &&
                   dateTime.Year == entity.CreationDate.Year);
        }

        private void InitializeDropDowns()
        {
            ViewBag.TakenAts = takenAtService.GetAll();
            ViewBag.FoodTypes = foodTypeService.GetAll();
        }
    }
}

MainSite/Views/FoodRegister/CreatePartial.cshtml
@using MainSite.Models
@model MainSite.Models.FoodRegisterViewModel
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <span class="h4 modal-title" id="TakenAtTitle"></span>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            @*TODO: Set the UpdateTargetId*@
            @using (Ajax.BeginForm("Create", "FoodRegister", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.InsertAfter, OnSuccess = "close()" }, new { role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="modal-body">


                    @Html.ValidationSummary(true)

                    @Html.HiddenFor(m => m.Id)
                    @Html.HiddenFor(m => m.TakenAtId)
                    <div class="form-group">
                        @Html.LabelFor(m => m.Description)
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", rows = "3" })
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.FoodTypeId)
                        @Html.DropDownListFor(m => m.FoodTypeId, new SelectList(ViewBag.FoodTypes, "Id", "Description"), new { @class = "form-control" })
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save changes" />
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

MainSite/Views/FoodRegister/FoodRegisterPanelPartial.cshtml
<div class="row">
    <div data-bind="foreach: FoodRegisters">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="h3 panel-title" data-bind="text: TakenAt"></span>
                    <span class="glyphicon glyphicon-remove pull-right"
                        data-bind="popover: { template: 'popoverTemplate', title: 'Confirm Remove', placement: 'bottom' }, visible: canEdit"></span>

                    <script type="text/html" id="popoverTemplate">
                        Are you shure you want to remove this entry?
                        <button class="btn  btn-danger" data-dismiss="popover" data-bind="click: $root.remove">Yes</button>
                        <button class="btn  btn-default" data-dismiss="popover">No</button>
                    </script>
                </div>
                <div class="panel-body">
                    <b>Description: </b><i data-bind="text: Description"></i>
                    <br />
                    <b>Date: </b><i data-bind="text: CreationDate"></i>
                    <br />
                    <b>Food Characterisc: </b><i data-bind="text: FoodType"></i>
                    <span class="glyphicon glyphicon-edit pull-right" data-bind="click: $root.edit, visible: canEdit "></span>
                </div>
            </div>
        </div>
    </div>
</div>

MainSite/Views/FoodRegister/Index.cshtml
@using Entity.Capture
@using MainSite.Models

@{
    ViewBag.Title = "Your Food Record";
    ViewBag.ServerDate = DateTime.Now;
}

<div class="content-wrapper col-lg-12 center-block">
    <nav class="navbar navbar-default" role="navigation" style="margin: 10px">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <form class="navbar-form form-inline navbar-left" role="form">
                <button type="button" class="btn btn-default" id="btnAddBreakfast">
                    Add Breakfast
                </button>
                <button type="button" class="btn btn-default" id="btnAddLunch">
                    Add Lunch
                </button>
                <button type="button" class="btn btn-default" id="btnAddDinner">
                    Add Dinner
                </button>
                <button type="button" class="btn btn-info" data-bind="click: $root.refreshAll">
                    <i class="glyphicon glyphicon-refresh"></i>
                </button>
            </form>
            <span class="navbar-text navbar-right">
                @if (Request.IsAuthenticated)
                {
                    <text>
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-form navbar-right" }))
                    {
                        <text>
                        Hello, @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "navbar-link ", title = "Manage" })
                        </text>
                        @Html.AntiForgeryToken()
<a href="javascript:document.getElementById('logoutForm').submit()" class="navbar-link"><span class="glyphicon glyphicon-log-out" title="logout"></span></a>
                    }
                    </text>
                }
            </span>
        </div>
    </nav>

    <div class="row">
        <div class="col-lg-3">
            <span class="h4">Showing elements for: </span>
            <span class="form-group" style="position: fixed; margin-left: 20px; width: 15%;">
                <div class="input-group date" id="dp3">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    <input class="form-control" type="text" readonly="readonly" id="dateControl" value="" />
                </div>
            </span>
        </div>
    </div>
    <br />
    <br />
    @{
        Html.RenderPartial("FoodRegisterPanelPartial");
        Html.RenderPartial("CreatePartial", new FoodRegisterViewModel());
    }
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/notify")
    <script type="text/javascript">
        $(function () {
            $("[data-toggle=popover]").popover();
            initPanels();
            var model = new Model();
            $(".input-group.date")
                .datepicker({
                    autoclose: true,
                    todayHighlight: true,
                    endDate: new Date(@ViewBag.ServerDate.Year,@(ViewBag.ServerDate.Month - 1),@ViewBag.ServerDate.Day),
                    startView: 0,
                    todayButton: true,
                    format: 'mm/dd/yyyy'
                })
                .on("changeDate", function (e) {
                    model.refresh(e.date);
                });
            ;
            model.refresh($("#dp3").datepicker('getDate'));
            $("#dateControl").val(dateFormat($("#dp3").datepicker('getDate'), "mm/dd/yyyy"));
            ko.applyBindings(model);
            closeModal(model);
        });

            function initPanels() {
                $("#btnAddBreakfast").click(function (e) {
                    $("#myModal").modal();
                    $("#TakenAtId").val(@( ((List<TakenAt>)(@ViewBag.TakenAts)).FirstOrDefault(m => m.Name == "Breakfast").Id));
                    $("#TakenAtTitle").text('Add @( ((List<TakenAt>)(@ViewBag.TakenAts)).FirstOrDefault(m => m.Name == "Breakfast").Description)');
                });

                $("#btnAddLunch").click(function (e) {
                    $("#myModal").modal();
                    $("#TakenAtId").val(@( ((List<TakenAt>)(@ViewBag.TakenAts)).FirstOrDefault(m => m.Name == "Launch").Id));
                    $("#TakenAtTitle").text('Add @( ((List<TakenAt>)(@ViewBag.TakenAts)).FirstOrDefault(m => m.Name == "Launch").Description)');
                });

                $("#btnAddDinner").click(function (e) {
                    $("#myModal").modal();
                    $("#TakenAtId").val(@( ((List<TakenAt>)(@ViewBag.TakenAts)).FirstOrDefault(m => m.Name == "Dinner").Id));
                    $("#TakenAtTitle").text('Add @( ((List<TakenAt>)(@ViewBag.TakenAts)).FirstOrDefault(m => m.Name == "Dinner").Description)');
                });
            }

            function closeModal(modal) {
                $("#myModal").on('hidden.bs.modal', function (e) {
                    $("#TakenAtId").val(-1);
                    $("#TakenAtTitle").text("");
                    $("#Description").val("");
                    $("#FoodTypeId").val(1);
                    modal.refresh($("#dp3").datepicker('getDate'));
                    $('#form0').attr('action', '@Url.Action("Create")');                    
                });
            }

            function close() {
                $("#myModal").modal('hide');
                showMessage("Data saved successfully!", "success");
            }

            function showMessage(message, style) {
                $.notify(message, style);
            }

            function Model() {
                var self = this;

                self.FoodRegisters = ko.observableArray(null);

                self.refreshAll = function () {
                    self.refresh($("#dp3").datepicker('getDate'));
                };

                self.remove = function (evt) {
                    $.getJSON('@Url.Action("Remove")', { id: evt.Id }, function (data) {
                        showMessage(data, "info");
                        self.refresh($("#dp3").datepicker('getDate'));
                    }).fail(function () {
                        showMessage("Error removing the data.", "error");
                    });
                };

                self.edit = function (evt) {
                    $('#form0').attr('action', '@Url.Action("Edit")');
                    $("#Id").val(evt.Id());
                    $("#TakenAtId").val(evt.TakenAtId());
                    $("#Description").val(evt.Description());
                    $('#FoodTypeId option[value="' + evt.FoodTypeId() + '"]').prop('selected', 'selected');
                    $("#myModal").modal('show');
                    $("#TakenAtTitle").text("Edit " + evt.TakenAt());
                };
                self.refresh = function (date) {
                    var date = dateFormat(date, "mm/dd/yyyy HH:MM:ss");
                    $.getJSON('@Url.Action("GetFoodRegistersByLoggedUserAndDate")', { date: date }, function (data) {
                        if (data === null) {
                            showMessage("The server can't search records for this date.", "error");
                            return;
                        }
                        if (data.Message !== undefined && data.Message !== "") {
                            showMessage(data.Message, "error");
                        }
                        if (data.length <= 0) {
                            showMessage("No data found for this date", "info");
                        }
                        ko.mapping.fromJS(data, {
                            create: function (options) {
                                now = new Date(@ViewBag.ServerDate.Year,@(ViewBag.ServerDate.Month - 1),@ViewBag.ServerDate.Day);
                                creationDate = new Date(options.data.CreationDate);
                                var innerModel = ko.mapping.fromJS(options.data);
                                innerModel.canEdit = now.getFullYear() == creationDate.getFullYear()
                                    && now.getMonth() == creationDate.getMonth()
                                    && now.getDate() == creationDate.getDate();
                                return innerModel;
                            }
                        }, self.FoodRegisters);
                    }).fail(function () {
                        showMessage("Error refreshing the data.", "error");
                    });
                };
                }
    </script>

}